services:
  postgres:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales
    volumes:
      - C:/DockerVolumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "2000:5433"
    networks:
      - sales-network
    command: >
      postgres -c listen_addresses='*' 
              -c work_mem=1GB 
              -c maintenance_work_mem=3GB
              -c shared_buffers=2GB
              -c statement_timeout=0

  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "3030:80"
    depends_on:
      - postgres
    networks:
      - sales-network

  airflow-init:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow_init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/sales
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    entrypoint : /bin/bash
    command: -c 'airflow db init && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@admin.com'
    depends_on:
      - postgres
    networks:
      - sales-network
  
  airflow-webserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/sales
      AIRFLOW__CORE__FERNET_KEY: 'FB0o_zt4e3Ziq4wwjZsFN6J_MKuPcHVD4mwTk8qGf4M='
      AIRFLOW__CORE__SECRET_KEY: 'FB0o_zt4e3Ziq4wwjZsFN6J_MKuPcHVD4mwTk8qGf4M='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__WORKERS: 4
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-init
      - postgres
    networks:
      - sales-network

  airflow-scheduler:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow_scheduler 
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/sales
      AIRFLOW__CORE__FERNET_KEY: 'FB0o_zt4e3Ziq4wwjZsFN6J_MKuPcHVD4mwTk8qGf4M='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow/data
    command: scheduler
    depends_on:
      - airflow-webserver
    networks:
      - sales-network

  dbt:
    build:
      context: ./dbt
      dockerfile: dockerfile
    container_name: dbt1
    environment:
        DBT_PROFILES_DIR: /usr/app
    volumes:
      - ./dbt:/usr/app
    ports:
      - "4040:4040"
    depends_on:
      - postgres
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge
  postgres-data: 
    driver: local